fix: githooks

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -3,15 +3,12 @@
 
 echo 'commit linting...'
 
-# npx --no -- commitlint --edit $1
-
 if  npx --no -- commitlint --edit $1
 then
-	echo 'inside'
- 	# $(exec < /dev/tty && node_modules/.bin/cz --hook) || true
-else 
-	echo 'error'
-	$(exec < /dev/tty && node_modules/.bin/cz --hook) || true
- fi
+    echo 'inside'
+else
+    echo 'error'
+    exec < /dev/tty && node_modules/.bin/cz --hook || true
+fi
 
 echo $success
